name: Paparazzi Tests

on: pull_request

jobs:
  paparazzi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: verifyPaparazziDebug
